---
- name: Get local HEAD commit
  command: git rev-parse HEAD
  args:
    chdir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"
  changed_when: false
  register: local_head

- name: Get remote HEAD commit
  command: "git ls-remote {{ git_repo_url }} HEAD"
  become_user: "{{ run_as_user }}"
  environment:
    GIT_SSH_COMMAND: "ssh{% if ssh_key_location is defined %} -i {{ ssh_key_location }}/id_ed25519 -o UserKnownHostsFile={{ ssh_key_location }}/known_hosts{% endif %}"
  changed_when: false
  register: remote_head

- name: Skip remaining tasks if no new commits to pull
  meta: end_host
  when: local_head.stdout == remote_head.stdout.split()[0]

# Gather data about CMS/CRM updates needed.
- name: Set drush path
  set_fact:
    drush: drush

- name: Gather facts
  setup:

- name: Start phasing out civicrm_custom_path - especially for Standalone
  set_fact:
    extensions_path: "{{ 'ext' if cms == 'Standalone' else civicrm_custom_path + '/extensions' }}"

- name: Set drush path (D9+)
  set_fact:
    drush: "{{ gitroot }}/vendor/bin/drush"
  when: cms == 'Drupal8' and freeze_cms != "1"

- name: Get current Drupal core version
  command: "{{ drush }} -y --root={{ webroot }} status --fields=drupal-version --field-labels=0"
  register: latest_civi_core_version
  become_user: "{{ run_as_user }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"
  changed_when: no
  when: cms == 'Drupal' and contract_type is search("Drupal Maintenance") and freeze_cms != "1"

- name: See if WP core needs updating
  command: wp core check-update --field=version --format=csv
  args:
    chdir: "{{ webroot }}"
  register: latest_wp_core_version
  changed_when: false
  failed_when: false
  when: cms == 'WordPress' and contract_type is search("WordPress Maintenance") and freeze_cms != "1"

  # Unfortunately, must be unconditional, because the condition is against the first host, which may not have Civi.
- name: Get the latest CiviCRM version number
  local_action:
    module: uri
    url: https://latest.civicrm.org/stable.php
    return_content: yes
  run_once: true
  changed_when: false
  failed_when: false
  become: no
  register: civi_ver
  when: freeze_crm != "1"

- name: check installed CiviCRM version
  command: "mysql -u{{ db_user }} -p{{ lookup('community.general.passwordstore', client + '/' + hostname + '/' + bare_url + '/mysql') }} {{ crm_db_name }} -N -s -e'SELECT version from civicrm_domain WHERE id = 1'"
  register: installed_civi_version
  changed_when: false
  when: contract_type is search("Civi Maintenance") and freeze_crm != "1" and civicrm == 'Yes'

# Delete old backups and make new backups.
- name: Find old CMS database backups
  find:
    age: 1d
    path: "{{ sqldumps_path }}"
    patterns: "{{ cms_db_name }}.upgradebackup.sql.gz"
    age_stamp: ctime
  register: old_cms_db_backups
  when: contract_type is search("Maintenance") and freeze_cms != "1"

- name: Delete old CMS database backups
  file:
    path: "{{ item.path }}"
    state: absent
  become_user: "{{ run_as_user }}"
  with_items: "{{ old_cms_db_backups.files }}"
  when: old_cms_db_backups.files is defined and old_cms_db_backups.matched > 0 and freeze_cms != "1"

- name: Check if CMS db backup already exists
  stat:
    path: "{{ sqldumps_path }}/{{ cms_db_name }}.upgradebackup.sql.gz"
  register: existing_cms_backup
  become_user: "{{ run_as_user }}"
  when: freeze_cms != "1"

- name: Back up the CMS database
  shell: "mysqldump --single-transaction {{ cms_db_name }} | gzip --rsyncable > {{ sqldumps_path }}/{{ cms_db_name }}.upgradebackup.sql.gz"
  become_user: "{{ run_as_user }}"
  when: existing_cms_backup.stat is defined and existing_cms_backup.stat.exists == false and freeze_cms != "1" and env == 'Live'

- block:
  - name: Find old Civi database backups
    find:
      age: 1d
      path: "{{ sqldumps_path }}"
      patterns: "{{ crm_db_name }}.upgradebackup.sql.gz"
      age_stamp: ctime
    register: old_db_backups

  - name: Delete old Civi database backups
    file:
      path: "{{ item.path }}"
      state: absent
    become_user: "{{ run_as_user }}"
    with_items: "{{ old_db_backups.files }}"
    when: old_db_backups.files is defined and old_db_backups.matched > 0

  - name: Check if Civi db backup already exists
    stat:
      path: "{{ sqldumps_path }}/{{ crm_db_name }}.upgradebackup.sql.gz"
    register: existing_backup
    become_user: "{{ run_as_user }}"

  - name: Back up the CRM database
    shell: "mysqldump --single-transaction --routines {{ crm_db_name }} | gzip --rsyncable > {{ sqldumps_path }}/{{ crm_db_name }}.upgradebackup.sql.gz"
    become_user: "{{ run_as_user }}"
    when: existing_backup.stat is defined and existing_backup.stat.exists == false
  when: contract_type is search("Civi Maintenance") and freeze_crm != "1" and civicrm == 'Yes' and env == 'Live'


# git pull.  Try to do this as late as possible so upgrades aren't pending for long.
- name: git pull
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ gitroot }}"
    umask: "{{ umask }}"
    track_submodules: no
    key_file: "{{ ssh_key_location + '/id_ed25519' if ssh_key_location is defined else omit }}"
    ssh_opts: "{{ '-o UserKnownHostsFile=' + ssh_key_location + '/known_hosts' if ssh_key_location is defined else omit }}"
  become_user: "{{ run_as_user }}"
  when:  freeze_crm != "1" or freeze_cms != "1"
  register: git_pull_result
  notify:
    - clear Drupal cache

- name: Check if CiviCRM files changed in git pull
  command: "git diff --name-only {{ git_pull_result.before }} {{ git_pull_result.after }} -- {{ civiroot }} {{ extensions_path }}"
  args:
    chdir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"
  register: civi_changed_files
  changed_when: civi_changed_files.stdout != ""
  when:
    - civicrm == 'Yes'
    - git_pull_result is changed
    - git_pull_result.before is not none
  notify: cv flush

- name: Composer install (D8)
  composer:
    command: install
    working_dir: "{{ gitroot }}"
    composer_executable: "{{ ansible_env.HOME + '/bin/composer' if 'mayfirst_ng_site' in group_names else '/usr/local/bin/composer' }}"
    executable: "{{ php_path|default(omit) }}" 
  become_user: "{{ run_as_user }}"
  when: cms == "Drupal8" and freeze_cms != "1"

# Civi updates
- block:

  - name: Check for pending extension database updates
    shell: "PATH=$HOME/bin:$PATH;cv ev 'return (bool) (CRM_Core_BAO_Domain::isDBUpdateRequired() || CRM_Extension_Upgrades::hasPending());' --cwd {{ webroot }}"
    become_user: "{{ run_as_user }}"
    environment:
      PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/bin"
    changed_when: false
    register: pending_updates

  - name: Run extension database updates
    shell: "PATH=$HOME/bin:$PATH;cv -n updb --cwd {{ webroot }}"
    become_user: "{{ run_as_user }}"
    environment:
      PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/bin"
    when: pending_updates.stdout == "true"

  
  when: contract_type is search("Civi Maintenance") and freeze_crm != "1" and civicrm == 'Yes'
  become_user: "{{ run_as_user }}"

# Drupal updates
- name: Check for Drupal database updates
  command: "{{ drush }} -y --root={{ webroot }} updbst"
  become_user: "{{ run_as_user }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"
  changed_when: no
  register: drupal_updatedb_status
  when: (cms == 'Drupal' or cms == 'Drupal8') and contract_type is search("Drupal Maintenance") and freeze_cms != "1"

- name: Run database updates
  ansible.builtin.command: "{{ drush }} -y --root={{ webroot }} updatedb"
  become_user: "{{ run_as_user }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"
  when: freeze_cms != "1" and (cms == 'Drupal' or cms == 'Drupal8') and contract_type is search("Drupal Maintenance") and not(drupal_updatedb_status.stdout == 'No database updates required' or drupal_updatedb_status.stderr == ' [success] No pending updates.')

# WP updates
- block:
  - name: Upgrade the WP DB
    command: "wp core update-db --path='{{ webroot }}'"
    become_user: "{{ run_as_user }}"
    environment:
      PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/bin"
    when: latest_wp_core_version.stdout is defined and latest_wp_core_version.stdout != "" and freeze_cms != "1"

  - name: Clear "last updated" times so plugin updates are reflected in monitoring
    command: "wp transient delete --network --all --path='{{ webroot }}'"
    become_user: "{{ run_as_user }}"
    changed_when: false
  when: cms == 'WordPress' and contract_type is search("WordPress Maintenance") and freeze_cms != "1"

- name: Flush permalink cache
  command: "wp rewrite flush --path='{{ webroot }}'"
  become_user: "{{ run_as_user }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/bin"
  when: cms == 'WordPress' and freeze_cms != "1"
